import Vue from 'vue'
import { Tab, Tabs, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Lazyload, Grid, GridItem, Icon, Sidebar, SidebarItem, Rate, ActionSheet, Dialog, Checkbox, CheckboxGroup, CouponCell, CouponList, SubmitBar } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(SubmitBar)
Vue.use(CouponCell)
Vue.use(CouponList)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Rate)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(NavBar)
Vue.use(Search)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Toast)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
